[application]

# App (Project) Name
name = "unified-markdown-editor"

# Dioxus App Default Platform
# desktop, web
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "unified-markdown-editor"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = []

icon = []

resources = []

# Javascript code file
script = ["/assets/functions.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.dioxuslabs"
publisher = "DioxusLabs"
icon = ["/assets/icon.ico"]